<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

This notebook aims to provide functions that produces anchor boxes as decribe in the paper.

In [1]:
import numpy as np

In [4]:
image_test = np.random.randn(800,800)
image_test_feature = np.random.randn(50,50)

In [45]:
def anchor_box(center, ratio, scale, shape_initial):
    width = shape_initial[0]
    height = shape_initial[1]
    anchor_width = width*scale*np.sqrt(ratio)
    anchor_height = height*scale/np.sqrt(ratio)
    
    ym = center[1] - anchor_height/2
    yp = center[1] + anchor_height/2
    xm = center[0] - anchor_width/2
    xp = center[0] + anchor_width/2
    
    anchor = np.array((ym,yp,xm,xp))
    return(anchor)

In [46]:
anchor_box((10,20),2,3,(100,100))

array([ -86.06601718,  126.06601718, -202.13203436,  222.13203436])

In [40]:
def list_centers(shape_initial, shape_featured):
    ratio_h = shape_initial[1]/shape_featured[1]
    ratio_w = shape_initial[0]/shape_featured[0]
    #intiail center is the center at the left top corner
    all_centers = [np.array((ratio_w/2, ratio_h/2),dtype=float) + np.array((ratio_w*i, ratio_h*j),dtype=float) for i in range(int(shape_featured[0])) for j in range(int(shape_featured[1]))]
    return(all_centers)

In [47]:
def anchor_boxes(list_centers, list_ratios, list_scales, shape_initial):
    all_anchors = [anchor_box(center, ratio, scale,shape_initial) for center in list_centers for ratio in list_ratios
                   for scale in list_scales]
    return(all_anchors)

In [52]:
anchor_boxes(list_centers((800,800),(50,50)), [0.2,1,3],[1,2,3],(800,800))

[array([-886.427191 ,  902.427191 , -170.8854382,  186.8854382]),
 array([-1780.854382 ,  1796.854382 ,  -349.7708764,   365.7708764]),
 array([-2675.281573 ,  2691.281573 ,  -528.6563146,   544.6563146]),
 array([-392.,  408., -392.,  408.]),
 array([-792.,  808., -792.,  808.]),
 array([-1192.,  1208., -1192.,  1208.]),
 array([-222.94010768,  238.94010768, -684.82032303,  700.82032303]),
 array([ -453.88021535,   469.88021535, -1377.64064606,  1393.64064606]),
 array([ -684.82032303,   700.82032303, -2070.46096908,  2086.46096908]),
 array([-870.427191 ,  918.427191 , -170.8854382,  186.8854382]),
 array([-1764.854382 ,  1812.854382 ,  -349.7708764,   365.7708764]),
 array([-2659.281573 ,  2707.281573 ,  -528.6563146,   544.6563146]),
 array([-376.,  424., -392.,  408.]),
 array([-776.,  824., -792.,  808.]),
 array([-1176.,  1224., -1192.,  1208.]),
 array([-206.94010768,  254.94010768, -684.82032303,  700.82032303]),
 array([ -437.88021535,   485.88021535, -1377.64064606,  1393.64